const allCourses = [
  // Job-Oriented Specialization
  {
    id: 1,
    title: "Advanced Embedded System Design",
    description: "Course details...",
    image: "/courses/Advanced Embedded System Design.png",
    link: "/courses/advanced-embedded-system-design",
    category: "Job-Oriented Specialization",
    location: "Bangalore",
    experience: "2+ years",
  },
  {
    id: 2,
    title: "Advanced VLSI Design & Verification",
    description: "Course details...",
    image: "/courses/Advanced VLSI Design & Verification.png",
    link: "/courses/advanced-vlsi-design-verification",
    category: "Job-Oriented Specialization",
    location: "Hyderabad",
    experience: "3+ years",
  },
  {
    id: 3,
    title: "Advanced ASIC Verification (VLSI VM)",
    description: "Course details...",
    image: "/courses/Advanced ASIC Verification (VLSI VM).png",
    link: "/courses/advanced-asic-verification-vlsi-vm",
    category: "Job-Oriented Specialization",
    location: "Pune",
    experience: "2+ years",
  },
  {
    id: 4,
    title: "Advanced VLSI Design & DFT (VLSI DFT)",
    description: "Course details...",
    image: "/courses/Advanced VLSI Design & DFT (VLSI DFT).png",
    link: "/courses/advanced-vlsi-design-dft-vlsi-dft",
    category: "Job-Oriented Specialization",
    location: "Noida",
    experience: "3+ years",
  },
  {
    id: 5,
    title: "Advanced Physical Design & Verification (VLSI PD)",
    description: "Course details...",
    image: "/courses/Advanced Physical Design & Verification (VLSI PD).png",
    link: "/courses/advanced-physical-design-verification-vlsi-pd",
    category: "Job-Oriented Specialization",
    location: "Remote",
    experience: "4+ years",
  },

  // Academic Programs
  {
    id: 6,
    title: "VLSI Internship Program",
    description: "Course details...",
    image: "/courses/Advanced Embedded System Design (1).png",
    link: "/courses/vlsi-internship-program",
    category: "Academic Programs",
    location: "Chennai",
    experience: "N/A",
  },
  {
    id: 7,
    title: "Executive Courses Program",
    description: "Course details...",
    image: "/blog/blog2.jpg",
    link: "/courses/executive-courses-program",
    category: "Academic Programs",
    location: "Remote",
    experience: "1+ years",
  },

  // Emerging Technology
  {
    id: 8,
    title: "IoT – Internet of Things",
    description: "Course details...",
    image: "/courses/IoT – Internet of Things.png",
    link: "/courses/iot-internet-of-things",
    category: "Emerging Technology",
    location: "Bangalore",
    experience: "2+ years",
  },
  {
    id: 9,
    title: "Edge AI – Edge Artificial Intelligence",
    description: "Course details...",
    image: "/courses/Edge AI – Edge Artificial Intelligence.png",
    link: "/courses/edge-ai-edge-artificial-intelligence",
    category: "Emerging Technology",
    location: "Hyderabad",
    experience: "2+ years",
  },
  {
    id: 10,
    title: "RISC-V Architecture",
    description: "Course details...",
    image: "/courses/RISC-V Architecture.png",
    link: "/courses/risc-v-architecture",
    category: "Emerging Technology",
    location: "Pune",
    experience: "1+ years",
  },
  {
    id: 11,
    title: "ARM Architecture",
    description: "Course details...",
    image: "/blog/blog3.jpg",
    link: "/courses/arm-architecture",
    category: "Emerging Technology",
    location: "Remote",
    experience: "2+ years",
  },
  {
    id: 12,
    title: "IC Packaging & Manufacturing",
    description: "Course details...",
    image: "/blog/blog3.jpg",
    link: "/courses/ic-packaging-manufacturing",
    category: "Emerging Technology",
    location: "Noida",
    experience: "3+ years",
  },

  // VLSI Internship
  {
    id: 13,
    title: "Physical Design (PD)",
    description: "Internship details on Physical Design.",
    image: "/blog/blogf.jpg",
    link: "/internship/physical-design",
    category: "VLSI Internship",
    location: "Remote",
    experience: "N/A",
  },
  {
    id: 14,
    title: "Physical Verification (PV)",
    description: "Internship details on Physical Verification.",
    image: "/blog/blogf.jpg",
    link: "/internship/physical-verification",
    category: "VLSI Internship",
    location: "Chennai",
    experience: "N/A",
  },
  {
    id: 15,
    title: "Design For Testing (DFT)",
    description: "Internship details on Design For Testing.",
    image: "/blog/blogf.jpg",
    link: "/internship/design-for-testing",
    category: "VLSI Internship",
    location: "Bangalore",
    experience: "N/A",
  },
  {
    id: 16,
    title: "ASIC Design",
    description: "Internship details on ASIC Design.",
    image: "/blog/blogf.jpg",
    link: "/internship/asic-design",
    category: "VLSI Internship",
    location: "Hyderabad",
    experience: "N/A",
  },
  {
    id: 17,
    title: "Synthesis",
    description: "Internship details on Synthesis.",
    image: "/blog/blogf.jpg",
    link: "/internship/synthesis",
    category: "VLSI Internship",
    location: "Pune",
    experience: "N/A",
  },
  {
    id: 18,
    title: "Static Timing Analysis (STA)",
    description: "Internship details on Static Timing Analysis.",
    image: "/blog/blogf.jpg",
    link: "/internship/static-timing-analysis",
    category: "VLSI Internship",
    location: "Noida",
    experience: "N/A",
  },

  // Part-Time Courses
  {
    id: 19,
    title: "VLSI Design Methodology (PT)",
    description: "Part-time course...",
    image: "/blog/blog5.jpg",
    link: "/courses/vlsi-design-methodology-pt",
    category: "Part-Time Courses",
    location: "Chennai",
    experience: "2+ years",
  },
  {
    id: 20,
    title: "Advanced ASIC Verification (VLSI VM-PT)",
    description: "Part-time course...",
    image: "/blog/blog5.jpg",
    link: "/courses/advanced-asic-verification-vlsi-vm-pt",
    category: "Part-Time Courses",
    location: "Remote",
    experience: "3+ years",
  },

  // Online Courses
  {
    id: 21,
    title: "RTL Design using Verilog HDL",
    description: "Online course on RTL design using Verilog HDL.",
    image: "/blog/blog6.jpg",
    link: "/courses/rtl-design-verilog-hdl",
    category: "Online Courses",
    location: "Bangalore",
    experience: "2+ years",
  },
  {
    id: 22,
    title: "Design Stream (RTL, STA, Synthesis)",
    description: "Covers RTL, STA, and Synthesis.",
    image: "/blog/blog6.jpg",
    link: "/courses/design-stream-rtl-sta-synthesis",
    category: "Online Courses",
    location: "Hyderabad",
    experience: "2+ years",
  },
  {
    id: 23,
    title: "Verification Stream (UVM, SV)",
    description: "UVM and SystemVerilog courses.",
    image: "/blog/blog6.jpg",
    link: "/courses/verification-stream-uvm-sv",
    category: "Online Courses",
    location: "Pune",
    experience: "1+ years",
  },
  {
    id: 24,
    title: "Embedded Systems & IoT",
    description: "Courses on Embedded Systems and IoT.",
    image: "/blog/blog6.jpg",
    link: "/courses/embedded-systems-iot",
    category: "Online Courses",
    location: "Noida",
    experience: "2+ years",
  },
  {
    id: 25,
    title: "Core Electronics (DSP, RF, Device Physics)",
    description: "Covers DSP, RF, and Device Physics.",
    image: "/blog/blog6.jpg",
    link: "/courses/core-electronics-dsp-rf-device-physics",
    category: "Online Courses",
    location: "Chennai",
    experience: "2+ years",
  },
  {
    id: 26,
    title: "Emerging Tech (RISC-V, Edge AI, ARM)",
    description: "Covers RISC-V, Edge AI, and ARM.",
    image: "/blog/blog6.jpg",
    link: "/courses/emerging-tech-risc-v-edge-ai-arm",
    category: "Online Courses",
    location: "Remote",
    experience: "3+ years",
  },

  // Core Technical Courses
  {
    id: 27,
    title: "Semiconductor Physics and Device Modelling",
    description: "Study of semiconductor physics and modeling.",
    image: "/blog/blog7.jpg",
    link: "/courses/semiconductor-physics-device-modelling",
    category: "Core Technical Courses",
    location: "Bangalore",
    experience: "2+ years",
  },
  {
    id: 28,
    title: "Semiconductor Manufacturing & Process Technology",
    description: "Manufacturing processes and technology.",
    image: "/blog/blog7.jpg",
    link: "/courses/semiconductor-manufacturing-process-technology",
    category: "Core Technical Courses",
    location: "Hyderabad",
    experience: "3+ years",
  },
  {
    id: 29,
    title: "RF and Microwave Engineering",
    description: "Topics in RF and microwave engineering.",
    image: "/blog/blog7.jpg",
    link: "/courses/rf-microwave-engineering",
    category: "Core Technical Courses",
    location: "Pune",
    experience: "2+ years",
  },
  {
    id: 30,
    title: "Hardware Security and Reliability",
    description: "Ensuring hardware security.",
    image: "/blog/blog7.jpg",
    link: "/courses/hardware-security-reliability",
    category: "Core Technical Courses",
    location: "Noida",
    experience: "2+ years",
  },
  {
    id: 31,
    title: "PCB Design and Hardware Prototyping",
    description: "PCB design techniques and prototyping.",
    image: "/blog/blog7.jpg",
    link: "/courses/pcb-design-hardware-prototyping",
    category: "Core Technical Courses",
    location: "Chennai",
    experience: "1+ years",
  },
  {
    id: 32,
    title: "PLC – SCADA (Industrial Automation)",
    description: "PLC and SCADA systems.",
    image: "/blog/blog7.jpg",
    link: "/courses/plc-scada-industrial-automation",
    category: "Core Technical Courses",
    location: "Remote",
    experience: "2+ years",
  },
  {
    id: 33,
    title: "Industrial Electrical and Control Systems",
    description: "Industrial electrical systems and control.",
    image: "/blog/blog7.jpg",
    link: "/courses/industrial-electrical-control-systems",
    category: "Core Technical Courses",
    location: "Bangalore",
    experience: "2+ years",
  },
];
export default allCourses;
